/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites/index'
import { Route as BestPlayedIndexRouteImport } from './routes/best-played/index'
import { Route as AlbumsArtistRouteImport } from './routes/albums/$artist'
import { Route as AlbumsArtistAlbumRouteImport } from './routes/albums/$artist/$album'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestPlayedIndexRoute = BestPlayedIndexRouteImport.update({
  id: '/best-played/',
  path: '/best-played/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsArtistRoute = AlbumsArtistRouteImport.update({
  id: '/albums/$artist',
  path: '/albums/$artist',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsArtistAlbumRoute = AlbumsArtistAlbumRouteImport.update({
  id: '/$album',
  path: '/$album',
  getParentRoute: () => AlbumsArtistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums/$artist': typeof AlbumsArtistRouteWithChildren
  '/best-played': typeof BestPlayedIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/search': typeof SearchIndexRoute
  '/albums/$artist/$album': typeof AlbumsArtistAlbumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums/$artist': typeof AlbumsArtistRouteWithChildren
  '/best-played': typeof BestPlayedIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/search': typeof SearchIndexRoute
  '/albums/$artist/$album': typeof AlbumsArtistAlbumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums/$artist': typeof AlbumsArtistRouteWithChildren
  '/best-played/': typeof BestPlayedIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/albums/$artist/$album': typeof AlbumsArtistAlbumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums/$artist'
    | '/best-played'
    | '/favorites'
    | '/search'
    | '/albums/$artist/$album'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums/$artist'
    | '/best-played'
    | '/favorites'
    | '/search'
    | '/albums/$artist/$album'
  id:
    | '__root__'
    | '/'
    | '/albums/$artist'
    | '/best-played/'
    | '/favorites/'
    | '/search/'
    | '/albums/$artist/$album'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsArtistRoute: typeof AlbumsArtistRouteWithChildren
  BestPlayedIndexRoute: typeof BestPlayedIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-played/': {
      id: '/best-played/'
      path: '/best-played'
      fullPath: '/best-played'
      preLoaderRoute: typeof BestPlayedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$artist': {
      id: '/albums/$artist'
      path: '/albums/$artist'
      fullPath: '/albums/$artist'
      preLoaderRoute: typeof AlbumsArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$artist/$album': {
      id: '/albums/$artist/$album'
      path: '/$album'
      fullPath: '/albums/$artist/$album'
      preLoaderRoute: typeof AlbumsArtistAlbumRouteImport
      parentRoute: typeof AlbumsArtistRoute
    }
  }
}

interface AlbumsArtistRouteChildren {
  AlbumsArtistAlbumRoute: typeof AlbumsArtistAlbumRoute
}

const AlbumsArtistRouteChildren: AlbumsArtistRouteChildren = {
  AlbumsArtistAlbumRoute: AlbumsArtistAlbumRoute,
}

const AlbumsArtistRouteWithChildren = AlbumsArtistRoute._addFileChildren(
  AlbumsArtistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsArtistRoute: AlbumsArtistRouteWithChildren,
  BestPlayedIndexRoute: BestPlayedIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
